
language: python

# https://docs.travis-ci.com/user/multi-os/
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
matrix:
    include:
        # Ubuntu 16.04
        # https://docs.travis-ci.com/user/reference/xenial
        -   os: linux
            dist: xenial
            sudo: required
            python: 2.7

script:
-   cat ~/.travis/job_stages
-   cat /home/travis/.travis/job_stages
-   echo -e "export TRAVIS_HOME=/home/travis\n$(cat /home/travis/.travis/job_stages)" > /home/travis/.travis/job_stages
-   cat ~/.travis/job_stages
-   cat /home/travis/.travis/job_stages
