# https://docs.travis-ci.com/user/ci-environment/
language: python
python:
-   "3.5"
install:
-   sudo apt-get update -q
-   sudo apt-get purge postgr* 
-   sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade

# Install Virtualbox.
-   sudo apt-get -y install linux-headers-`uname -r`
-   sudo apt-get -y install -q build-essential virtualbox-ose-dkms virtualbox linux-headers-generic --fix-missing
-   sudo dpkg-reconfigure virtualbox-dkms
-   sudo dpkg-reconfigure virtualbox
-   sudo modprobe vboxdrv
-   sudo modprobe vboxnetflt
-   VBoxManage --version

# Install Vagrant.
# Find other releases at https://www.vagrantup.com/downloads.html
-   sudo wget -nv https://releases.hashicorp.com/vagrant/1.7.2/vagrant_1.7.2_x86_64.deb
-   sudo dpkg -i vagrant_1.7.2_x86_64.deb
#-   sudo wget -nv https://releases.hashicorp.com/vagrant/1.8.1/vagrant_1.8.1_x86_64.deb
#-   sudo dpkg -i vagrant_1.8.1_x86_64.deb
-   vagrant -v
-   sudo vagrant plugin install vagrant-cachier

-   sudo pip install tox
script:
-   tox
