
language: python

# https://docs.travis-ci.com/user/languages/python/
#python:
#-   "2.7"
#-   "3.3"
#-   "3.4"

# https://docs.travis-ci.com/user/multi-os/
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
matrix:
    include:
        # Ubuntu 14.04
        -   os: linux
            dist: trusty
            sudo: required
            python: 2.7

# https://docs.travis-ci.com/user/hosts
# Needed by DjTests.test_migrate
addons:
    hosts:
    -   test-dj-migrate-1
    -   test-dj-migrate-2

env:
    global:
    -   BURLAP_TEST_BOX=localhost

install:
-   sudo apt-key update
-   sudo apt-get -yq update
-   sudo apt-get -yq purge postgr*
-   sudo apt-get -yq purge virtualbox*
# The Oracle Java install routinely times out, and we're not using it, so uninstall it.
-   sudo apt-get -yq purge oracle-java*
-   sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade
-   sudo apt-get -yq install build-essential
-   sudo apt-get -yq --force-yes install linux-headers-`uname -r`
-   sudo apt-get -yq install pandoc
-   sudo pip install -r requirements-test.txt
#TODO: Get fab to test fab
#-  pip install -e .
# Deal with issue on Travis builders re: multiprocessing.Queue :(
#-   "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
#-   "pip install jinja2"
  
before_script:
# Allow us to SSH passwordless to localhost
-   ssh-keygen -f ~/.ssh/id_rsa -N ""
-   cp ~/.ssh/{id_rsa.pub,authorized_keys}
# Creation of an SSH agent for testing forwarding
-   eval $(ssh-agent)
-   ssh-add

script:
-  ./pep8.sh
-  tox -c tox-travis.ini -e py27
#-  tox -c tox-travis.ini -e py27 -- -s burlap/tests/functional_tests/test_js.py::JSTests::test_jshint
