# https://docs.travis-ci.com/user/ci-environment/
# Ubuntu 12.04 LTS Server Edition 64 bit

language: python

python:
-   "3.5"

# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
matrix:
    include:
        -   os: linux
            dist: trusty # Ubuntu 14.04
            sudo: required

install:
  
  # Build/test dependencies
  - pip install -r requirements.txt
  
  # Get fab to test fab
  - pip install -e .
  
  # Deal with issue on Travis builders re: multiprocessing.Queue :(
  #- "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
  #- "pip install jinja2"
  
  - sudo pip install tox pylint
  
before_script:

  # Allow us to SSH passwordless to localhost
  - ssh-keygen -f ~/.ssh/id_rsa -N ""
  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
  
  # Creation of an SSH agent for testing forwarding
  - eval $(ssh-agent)
  - ssh-add

# This works, but takes forever to run and usually times out.
#-   sudo apt-key update
#-   sudo apt-get update -q
#-   sudo apt-get purge postgr*
#-   sudo apt-get purge virtualbox*
#-   sudo apt-get -o Dpkg::Options::="--force-confnew" --force-yes -fuy dist-upgrade
#-   sudo apt-get -y install build-essential
#-   sudo apt-get -y --force-yes install linux-headers-`uname -r`

script:
#-   ./pep8.sh
#-   tox
-   "tox -e py27 -- -s burlap/tests/test_project.py::test_project"
